### ISSUE TITLE
报了一个错误

### ISSUE THREAD

**Issue by rilweic** [xw5xr6/revERNIEBot#1]
```
Traceback (most recent call last):
  File "/Users/lichao/PycharmProjects/drf_demo/python_test/chatai/yiyan.py", line 16, in <module>
    print(bot.ask("你好"))  # 获取回复
  File "/Users/lichao/.virtualenvs/drf_demo/lib/python3.9/site-packages/revERNIEBot/selenium/__init__.py", line 148, in ask
    if resp_json['data']['botChat']['message'][0]['content'] != "正在生成中...":
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function ChatBot.__del__ at 0x1089a8160>
Traceback (most recent call last):
  File "/Users/lichao/.virtualenvs/drf_demo/lib/python3.9/site-packages/revERNIEBot/selenium/__init__.py", line 101, in __del__
  File "/Users/lichao/.pyenv/versions/3.9.0/lib/python3.9/_sitebuiltins.py", line 26, in __call__
SystemExit: None
```

**Comment by rilweic** [comment]
看了一下请求结果，应该是不行了
![image](https://user-images.githubusercontent.com/9164714/226911363-a49e26cd-2a17-4f9c-ba3c-a83816b573cc.png)

**Comment by xw5xr6** [comment]
这么快就被封了，麻烦等明天修复

**Comment by xw5xr6** [comment]
已修复，请执行`pip3 install --upgrade revERNIEBot`以更新

**Comment by rilweic** [comment]
![image](https://user-images.githubusercontent.com/9164714/227077100-1a22ffb1-b74d-4995-801d-162727c75290.png)
是又被封了吗

**Comment by xw5xr6** [comment]
更新了库吗?我这没有这个问题

**Comment by rilweic** [comment]
![Uploading image.png…]()
更新了

**Comment by RockChinQ** [comment]
哦确实出问题了，待会儿看看

**Comment by rilweic** [comment]
> 更新了库吗?我这没有这个问题

我这边在mac上执行也有同样的问题，截图是放到服务器上执行的截图

**Comment by xw5xr6** [comment]
已在最新版修复
