### ISSUE TITLE
出了个错误

### ISSUE THREAD

**Issue by rilweic** [xw5xr6/revERNIEBot#3]
![image](https://user-images.githubusercontent.com/9164714/227265609-a4050ca2-5e60-48a4-8f3d-5cc96599123d.png)
```
Traceback (most recent call last):
  File "/root/wxyy/yiyan.py", line 18, in <module>
    print(bot.ask("帮我画一个小猪"))  # 获取回复
  File "/usr/local/python3/lib/python3.9/site-packages/revERNIEBot/selenium/__init__.py", line 159, in ask
    if resp_json['data']['botChat']['message'][0]['content'] != "正在生成中...":
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function ChatBot.__del__ at 0x7f22ef359e50>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/revERNIEBot/selenium/__init__.py", line 108, in __del__
  File "/usr/local/python3/lib/python3.9/_sitebuiltins.py", line 26, in __call__
SystemExit: None
```
使用的最新的版本

![image](https://user-images.githubusercontent.com/9164714/227265863-6cccc7af-4359-4933-b9db-65b28d34add8.png)

**Comment by xw5xr6** [comment]
文字回复正常吗？目前还没支持图片

**Comment by rilweic** [comment]
> 文字回复正常吗？目前还没支持图片

也有问题呢
<img width="968" alt="image" src="https://user-images.githubusercontent.com/9164714/227397347-82337cd4-7cdd-4b5b-adc4-06ee7f2f6f99.png">

**Comment by xw5xr6** [comment]
确实，新的反爬策略🤣

**Comment by xw5xr6** [comment]
0.0.7修了

**Comment by xw5xr6** [comment]
注意目前初始化ChatBot时请不要再携带chromedriver路径的参数
